development:
  cloud_name: hos3ptowg
  api_key: '938161817367682'
  api_secret: qhLdU8Q52d11j5ZcLYeHnBmuPZ0
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hos3ptowg
  api_key: '938161817367682'
  api_secret: qhLdU8Q52d11j5ZcLYeHnBmuPZ0
  enhance_image_tag: true
  static_image_support: false
test:
  cloud_name: hos3ptowg
  api_key: '938161817367682'
  api_secret: qhLdU8Q52d11j5ZcLYeHnBmuPZ0
  enhance_image_tag: true
  static_image_support: false